#!/bin/bash
set -e

# Restore backup
for VER in "2.1" "3.0"; do
    FILE1="/usr/lib/surface-go-wifi/backup/hw$VER/board.bin"
    if [[ -f "$FILE1" ]]; then
        FILE2="/lib/firmware/ath10k/QCA6174/hw$VER/board.bin"
        cp "$FILE1" "$FILE2"
    fi
done

exit 0
