#!/bin/bash
set -e

# Make backup
for VER in "2.1" "3.0"; do
    FILE1="/lib/firmware/ath10k/QCA6174/hw$VER/board.bin"
    if [[ -f "$FILE1" ]]; then
        FILE2="/usr/lib/surface-go-wifi/backup/hw$VER/board.bin"
        if [[ ! -f "$FILE2" ]]; then
            cp "$FILE1" "$FILE2"
        fi
    fi
done

# First install
FILE1="/usr/lib/surface-go-wifi/board.bin"
for VER in "2.1" "3.0"; do
    FILE2=/lib/firmware/ath10k/QCA6174/hw$VER/board.bin
    cp $FILE1 $FILE2
done

# Done
exit 0
