#!/bin/bash
set -e

# Make the initial backup
for VER in "2.1" "3.0"; do
    FILE1="/lib/firmware/ath10k/QCA6174/hw$VER/board.bin"
    if [[ -f "$FILE1" ]]; then
        FILE2="/usr/lib/surface-go-wifi/backup/hw$VER/board.bin"
        if [[ ! -f "$FILE2" ]]; then
            cp "$FILE1" "$FILE2"
        fi
    fi
done

# Invoke for the first time
/usr/lib/surface-go-wifi/bin/restore

# APT script
cat << EOF > /etc/apt/apt.conf.d/84-surface-go-wifi
APT::Install::Post-Invoke-Success {
  "[ -f /usr/lib/surface-go-wifi/bin/restore ] && /usr/lib/surface-go-wifi/bin/restore || true";
};
EOF

# Done
exit 0
